// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0Eb9sC04dtqaRsTOM-DDc13KPmS3NGI',
    appId: '1:503369772931:web:ae93075fafd871c579d0b6',
    messagingSenderId: '503369772931',
    projectId: 'instafirecrd01',
    authDomain: 'instafirecrd01.firebaseapp.com',
    storageBucket: 'instafirecrd01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3MwIsV5jx4EY5esJkfOg01JUPqqYfDs',
    appId: '1:503369772931:android:e8e8030207c9355479d0b6',
    messagingSenderId: '503369772931',
    projectId: 'instafirecrd01',
    storageBucket: 'instafirecrd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYSMIa092SGtB7Q7JL6LHOuddQK1bFEA',
    appId: '1:503369772931:ios:6d3b69882e0a8d9a79d0b6',
    messagingSenderId: '503369772931',
    projectId: 'instafirecrd01',
    storageBucket: 'instafirecrd01.appspot.com',
    iosClientId: '503369772931-0bis4o9ti40drn8m3hnv25bfmtmbekou.apps.googleusercontent.com',
    iosBundleId: 'com.example.instafire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASYSMIa092SGtB7Q7JL6LHOuddQK1bFEA',
    appId: '1:503369772931:ios:6d3b69882e0a8d9a79d0b6',
    messagingSenderId: '503369772931',
    projectId: 'instafirecrd01',
    storageBucket: 'instafirecrd01.appspot.com',
    iosClientId: '503369772931-0bis4o9ti40drn8m3hnv25bfmtmbekou.apps.googleusercontent.com',
    iosBundleId: 'com.example.instafire',
  );
}
